spring.application.name=project

spring.datasource.url=jdbc:postgresql://localhost:5432/yourdatabase
spring.datasource.username=username
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#set path as mandatory for all api of this project
server.servlet.context-path=/api/v1 


